spring:
  application:
    name: libraryms
  config:
    activate:
      active: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./dbh2/librarymsdb;AUTO_SERVER=TRUE
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      platform: H2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
server:
  address: 0.0.0.0
  port: 12023
  servlet:
    context-path: /libraryms
    session:
      timeout: "P7D"
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0
springfox:
  documentation:
    swagger-ui:
      enabled: false
swagger.show: false
