spring:
  application:
    name: libraryms
  config:
    activate:
      active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./dbh2/librarymsdb;AUTO_SERVER=TRUE
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      platform: H2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
server:
  port: 12023
  servlet:
    context-path: /libraryms
    session:
      timeout: "P7D"
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
springfox:
  documentation:
    swagger-ui:
      enabled: true
swagger.show: true